### ISSUE TITLE
sdl and PKG_CONFIG_PATH environment variable

### ISSUE THREAD

**Issue by peepo** [mpenkov/ffmpeg-tutorial#10]
what to do with PKG_CONFIG_PATH environment variable?

cannot find SDL is there more info?

using wheezy

some error messages removed with:
$ ldd /usr/bin/ffmpeg
..
libavutil.so.51 => /usr/lib/x86_64-linux-gnu/libavutil.so.51 (0x00007f0873a04000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0873782000)
..
hence
$ export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
$ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/
but
$ cd ffmpeg-tutorial-master
$ make
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing`libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing`libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing`libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing`libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing`sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found

**Comment by cirosantilli** [comment]
On Ubuntu 15.10 you also need:

```
sudo apt-get install libsdl1.2-dev
```

I had installed `libsdl2-dev`, but it's not the one.
