### ISSUE TITLE
libavcodec/avcodec.h not found

### ISSUE THREAD

**Issue by fornof** [mpenkov/ffmpeg-tutorial#29]
> $ make
> mkdir -p obj
> mkdir -p bin
> gcc -Wall -ggdb tutorial01.c  -c -o obj/tutorial01.o
> tutorial01.c:20:32: fatal error: libavcodec/avcodec.h: No such file or directory
>  #include <libavcodec/avcodec.h>
>                                 ^
> compilation terminated.
> Makefile:34: recipe for target 'obj/tutorial01.o' failed
> make: **\* [obj/tutorial01.o] Error 1

I get this "libavcodec/avcodec.h not found"  when following the original tutorial and when trying to make  this tutorial.

**Comment by mpenkov** [comment]
The ffmpeg headers are missing. You need to install ffmpeg as described in the readme.
