### ISSUE TITLE
which version of ffmpeg should i use?

### ISSUE THREAD

**Issue by jiji879** [mpenkov/ffmpeg-tutorial#33]
when compile the code i found many attributes have been deprecated,like avcodec_default_get_buffer,avcodec_default_release_buffer,etc. so which version should i use for compiling this code?

**Comment by mpenkov** [comment]
See VERSION.txt for the most recent version of ffmpeg at the time of working on the project.

**Comment by jiji879** [comment]
on mac i use N-51481-g5c73645d91 instead of N-50314-gf6fff8e which can make me compile successfully
